import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import About from "../components/About";
import Resume from '@/components/Resume';
import Contact from '@/components/Contact';
import Project from '@/components/Project';
// import ScrollUpBtn from "../components/ScrollUpBtn";


export default function Home() {
  return (
    <>
      <Head>
        <title>CV - Sutha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <header>

        <nav className={styles.navbar}>
          <div className={styles.navlinks}>
            <div className={styles.title_nav}>
            <p>RADITYA.</p>
            </div>
          <div className={styles.nav_links}>
          <a className={styles.nav_a} href='#'>Home</a>
          <a className={styles.nav_a} href='#about'>About</a>
          <a className={styles.nav_a} href='#Project'>Project</a>
          <a className={styles.nav_a} href='#'>Contact</a>
          </div>
          </div>
        </nav>

        <div className={styles.header}>
          <div className={styles.left_content}>
            <div className={styles.ornamen}></div>
            <div className={styles.title_box}>
              <div className={styles.title}>
                <p> MY NAME IS <br></br> 
                <span className={styles.title_span}> MADE SUTHA RADITYA </span> </p>
              </div>
              <div className={styles.job}>
                <p> I Wanna Be A UI Developer </p>
              </div>
              <div className={styles.header_link}>
              <a href='#about' className={styles.header_a}> More </a>
              <div className={styles.arrow_box}>
              <div className={styles.arrow}></div>
              <div className={styles.arrow}></div>
              </div>
            </div>
            </div>
          </div>
          <div className={styles.right_content}>
            <div className={styles.top}></div>
            <div className={styles.bott}></div>
          </div>
        </div>
      </header>
      <About/>
      <Resume/>
      <Project/>
      <Contact/>
    </>
  )
}
